### ISSUE TITLE
support MultiError and VError.info better in cmdln.main()

### ISSUE THREAD

**Issue by trentm** [trentm/node-cmdln#18]
A common and intended usage of cmdln for one's command's main function is:

```
function main(argv) {
    var cli = new JoyentReposCli();
    cmdln.main(cli, {
        argv: argv || process.argv
    });
}
```

Currently this handles printing errors, e.g.:

```
$ jr oneach 'grep NODE_PREBUILT_TAG Makefile' sdc-nat triton-cmon
...
jr oneach: error: exec error in repo "sdc-nat": exec "/bin/bash -c grep NODE_PREBUILT_TAG Makefile": exited with status 1
```

and with `showErrStack`:

```
$ jr -v oneach 'grep NODE_PREBUILT_TAG Makefile' sdc-nat triton-cmon
...
jr oneach: error: VError: exec error in repo "sdc-nat": exec "/bin/bash -c grep NODE_PREBUILT_TAG Makefile": exited with status 1
    at WorkQueue.onProgress (/Users/trentm/joy/joyent-repos/lib/cli/do_oneach.js:122:33)
    at emitTwo (events.js:87:13)
    at WorkQueue.emit (events.js:172:7)
    at doneARepo (/Users/trentm/joy/joyent-repos/lib/jrm.js:718:11)
    at /Users/trentm/joy/joyent-repos/node_modules/vasync/lib/vasync.js:567:23
    at onExec (/Users/trentm/joy/joyent-repos/lib/jrm.js:712:17)
    at onChildExited (/Users/trentm/joy/joyent-repos/node_modules/forkexec/lib/forkexec.js:83:2)
    at /Users/trentm/joy/joyent-repos/node_modules/forkexec/lib/forkexec.js:53:4
    at ChildProcess.exithandler (child_process.js:207:5)
    at emitTwo (events.js:87:13)
```

* * *

At least in my and Joyent's cases, usage of [verror](https://github.com/joyent/node-verror) is common (cmdln uses it itself). VError supports:

- [MultiError](https://github.com/joyent/node-verror#reference-multierror) for grouping up errors (e.g. you get one of these from [vasync](https://github.com/joyent/node-vasync methods; also from more recent [VError.errorFromList](https://github.com/joyent/node-verror#verrorerrorfromlisterrors) usage; and
- [VError.info](https://github.com/joyent/node-verror#verrorinfoerr) to include programmatic plain object details on errors.

Currently the former isn't handled specially, so some error details aren't printed, e.g.:

```
$ jr oneach 'grep NODE_PREBUILT_TAG Makefile' sdc-nat triton-cmon sdc-rabbitmq
...
jr oneach: error: first of 2 errors: exec error in repo "sdc-rabbitmq": exec "/bin/bash -c grep NODE_PREBUILT_TAG Makefile": exited with status 1
```

and VError.info isn't used.

* * *

I'm going to change cmdln.main()'s error printing  as follows:

- If the err is a MultiError, then print all of collected errors' messages, e.g.:

```
$ jr oneach 'grep NODE_PREBUILT_TAG Makefile' sdc-nat triton-cmon sdc-rabbitmq
...
jr oneach: error: 2 errors:
    exec error in repo "sdc-rabbitmq": exec "/bin/bash -c grep NODE_PREBUILT_TAG Makefile": exited with status 1
    exec error in repo "sdc-nat": exec "/bin/bash -c grep NODE_PREBUILT_TAG Makefile": exited with status 1
```

- With `showErrStack` use `VError.fullStack()` to print the full cause chain.
- With `showErrStack` output `VError.info()` if there is any.

For example:

```
$ jr -v oneach 'grep NODE_PREBUILT_TAG Makefile' sdc-nat triton-cmon sdc-rabbitmq
...
jr oneach: error: 2 errors:
    exec error in repo "sdc-nat": exec "/bin/bash -c grep NODE_PREBUILT_TAG Makefile": exited with status 1
    exec error in repo "sdc-rabbitmq": exec "/bin/bash -c grep NODE_PREBUILT_TAG Makefile": exited with status 1
MultiError: first of 2 errors: exec error in repo "sdc-nat": exec "/bin/bash -c grep NODE_PREBUILT_TAG Makefile": exited with status 1
    at Function.VError.errorFromList (/Users/trentm/joy/joyent-repos/node_modules/verror/lib/verror.js:325:10)
    at WorkQueue.doneExecing (/Users/trentm/joy/joyent-repos/lib/cli/do_oneach.js:197:37)
    at emitNone (events.js:67:13)
    at WorkQueue.emit (events.js:166:7)
    at WorkQueue.dispatchNext (/Users/trentm/joy/joyent-repos/node_modules/vasync/lib/vasync.js:522:7)
    at /Users/trentm/joy/joyent-repos/node_modules/vasync/lib/vasync.js:569:7
    at onExec (/Users/trentm/joy/joyent-repos/lib/jrm.js:712:17)
    at onChildExited (/Users/trentm/joy/joyent-repos/node_modules/forkexec/lib/forkexec.js:83:2)
    at /Users/trentm/joy/joyent-repos/node_modules/forkexec/lib/forkexec.js:53:4
    at ChildProcess.exithandler (child_process.js:191:7)
caused by: VError: exec error in repo "sdc-nat": exec "/bin/bash -c grep NODE_PREBUILT_TAG Makefile": exited with status 1
    at WorkQueue.onProgress (/Users/trentm/joy/joyent-repos/lib/cli/do_oneach.js:122:33)
    at emitTwo (events.js:87:13)
    at WorkQueue.emit (events.js:172:7)
    at doneARepo (/Users/trentm/joy/joyent-repos/lib/jrm.js:718:11)
    at /Users/trentm/joy/joyent-repos/node_modules/vasync/lib/vasync.js:567:23
    at onExec (/Users/trentm/joy/joyent-repos/lib/jrm.js:712:17)
    at onChildExited (/Users/trentm/joy/joyent-repos/node_modules/forkexec/lib/forkexec.js:83:2)
    at /Users/trentm/joy/joyent-repos/node_modules/forkexec/lib/forkexec.js:53:4
    at ChildProcess.exithandler (child_process.js:207:5)
    at emitTwo (events.js:87:13)
caused by: VError: exec "/bin/bash -c grep NODE_PREBUILT_TAG Makefile": exited with status 1
    at interpretChildProcessResult (/Users/trentm/joy/joyent-repos/node_modules/forkexec/lib/forkexec.js:163:15)
    at onChildExited (/Users/trentm/joy/joyent-repos/node_modules/forkexec/lib/forkexec.js:75:9)
    at /Users/trentm/joy/joyent-repos/node_modules/forkexec/lib/forkexec.js:53:4
    at ChildProcess.exithandler (child_process.js:207:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:862:16)
    at Socket.<anonymous> (internal/child_process.js:338:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
caused by: VError: exited with status 1
    at interpretChildProcessResult (/Users/trentm/joy/joyent-repos/node_modules/forkexec/lib/forkexec.js:142:10)
    at onChildExited (/Users/trentm/joy/joyent-repos/node_modules/forkexec/lib/forkexec.js:75:9)
    at /Users/trentm/joy/joyent-repos/node_modules/forkexec/lib/forkexec.js:53:4
    at ChildProcess.exithandler (child_process.js:207:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:862:16)
    at Socket.<anonymous> (internal/child_process.js:338:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
error info:
    {
        "foo": "bar"
    }
```

My "error info: ... foo" example is obviously contrived.

**Comment by trentm** [comment]
This is in cmdln@4.4.0
