### ISSUE TITLE
tests fail against node 0.12

### ISSUE THREAD

**Issue by trentm** [trentm/node-cmdln#8]
see dap's https://gist.github.com/davepacheco/2da16db023666037495c

I can repro. E.g.: node 0.10:

```
[21:03:52 trentm@grape:~/tm/node-cmdln/test/cmd (master)]
$ DEBUG=1 node bwcompat-main-v1.js
Test out old v1 cmdln.main().

Usage:
    bwcompat-main-v1 [OPTIONS] COMMAND [ARGS...]
    bwcompat-main-v1 help COMMAND

Options:
    -h, --help      Show this help message and exit.

Commands:
    help (?)        Help on a specific sub-command.
bwcompat-main-v1: error: NoCommandError: no command given
    at /Users/trentm/tm/node-cmdln/lib/cmdln.js:446:29
    at CLI.printHelp (/Users/trentm/tm/node-cmdln/lib/cmdln.js:573:5)
    at CLI.emptyLine (/Users/trentm/tm/node-cmdln/lib/cmdln.js:445:10)
    at /Users/trentm/tm/node-cmdln/lib/cmdln.js:411:18
    at CLI.init (/Users/trentm/tm/node-cmdln/lib/cmdln.js:471:5)
    at CLI.init (/Users/trentm/tm/node-cmdln/test/cmd/bwcompat-main-v1.js:22:32)
    at CLI.main (/Users/trentm/tm/node-cmdln/lib/cmdln.js:398:10)
    at Object.main (/Users/trentm/tm/node-cmdln/lib/cmdln.js:789:9)
    at Object.<anonymous> (/Users/trentm/tm/node-cmdln/test/cmd/bwcompat-main-v1.js:26:11)
    at Module._compile (module.js:456:26)
```

vs. node 0.12:

```
$ DEBUG=1 ~/opt/node-0.12/bin/node bwcompat-main-v1.js
Test out old v1 cmdln.main().

Usage:
    bwcompat-main-v1 [OPTIONS] COMMAND [ARGS...]
    bwcompat-main-v1 help COMMAND

Options:
    -h, --help      Show this help message and exit.

Commands:
    help (?)        Help on a specific sub-command.
bwcompat-main-v1: error: WError: no command given
    at /Users/trentm/tm/node-cmdln/lib/cmdln.js:446:29
    at CLI.printHelp (/Users/trentm/tm/node-cmdln/lib/cmdln.js:573:5)
    at CLI.emptyLine (/Users/trentm/tm/node-cmdln/lib/cmdln.js:445:10)
    at /Users/trentm/tm/node-cmdln/lib/cmdln.js:411:18
    at CLI.init (/Users/trentm/tm/node-cmdln/lib/cmdln.js:471:5)
    at CLI.init (/Users/trentm/tm/node-cmdln/test/cmd/bwcompat-main-v1.js:22:32)
    at CLI.main (/Users/trentm/tm/node-cmdln/lib/cmdln.js:398:10)
    at Object.main (/Users/trentm/tm/node-cmdln/lib/cmdln.js:789:9)
    at Object.<anonymous> (/Users/trentm/tm/node-cmdln/test/cmd/bwcompat-main-v1.js:26:11)
    at Module._compile (module.js:460:26)
```

Note the error name diff. Something changed btwn node 0.10 and 0.12 in how we're sniffing the error name.

**Comment by trentm** [comment]
See these diffs. @davepacheco I realize this is likely hitting code paths in verror that *I* added, but I don't follow the difference here. Too late perhaps.

```
$ cat foo.js
var util = require('util');
var verror = require('verror');

function MyVError(msg) {
    verror.VError.call(this, msg);
}
util.inherits(MyVError, verror.VError);
//MyVError.prototype.name = 'WallaWallaError';

try {
    throw new MyVError('boom');
} catch (err) {
    console.log('err:', err)
    console.log('err.toString():', err.toString())
    console.log('err.stack:', err.stack)
}


[21:37:14 trentm@grape:~/tm/node-cmdln (master)]
$ ~/opt/node-0.10/bin/node foo.js
err: { [VError: boom] jse_shortmsg: 'boom', jse_summary: 'boom', message: 'boom' }
err.toString(): MyVError: boom
err.stack: MyVError: boom
    at new MyVError (/Users/trentm/tm/node-cmdln/foo.js:5:19)
    at Object.<anonymous> (/Users/trentm/tm/node-cmdln/foo.js:11:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3


[21:37:17 trentm@grape:~/tm/node-cmdln (master)]
$ ~/opt/node-0.12/bin/node foo.js
err: { [VError: boom] jse_shortmsg: 'boom', jse_summary: 'boom', message: 'boom' }
err.toString(): MyVError: boom
err.stack: VError: boom
    at new MyVError (/Users/trentm/tm/node-cmdln/foo.js:5:19)
    at Object.<anonymous> (/Users/trentm/tm/node-cmdln/foo.js:11:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Note that `err.stack` for node 0.12 doesn't get the constructor.name... but ends up getting the `VError.prototype.name`. Perhaps an intentional change in 0.12. Not sure.

**Comment by trentm** [comment]
Ah, I see the difference: I suspect node 0.10 was using `<err>.toString()` for the first line of `<err>.stack`, but no longer in node 0.12:

Here is foo.js without using verror.js to have a simpler test case:

```
$ cat foo.js
var util = require('util');

function MyError(msg) {
    Error.call(this);
    this.message = msg;
    Error.captureStackTrace(this, this.constructor);
}
util.inherits(MyError, Error);

MyError.prototype.toString = function () {
    return 'WallaWalla: ' + this.message;
};

try {
    throw new MyError('boom');
} catch (err) {
    console.log('err:', err)
    console.log('err.toString():', err.toString())
    console.log('err.stack:', err.stack)
}
```

And running that with 0.10 and 0.12:

```
$ ~/opt/node-0.10/bin/node foo.js
err: { [Error: boom] message: 'boom' }
err.toString(): WallaWalla: boom
err.stack: WallaWalla: boom
    at Object.<anonymous> (/Users/trentm/tm/node-cmdln/foo.js:15:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

[21:49:48 trentm@grape:~/tm/node-cmdln (master)]
$ ~/opt/node-0.12/bin/node foo.js
err: { [Error: boom] message: 'boom' }
err.toString(): WallaWalla: boom
err.stack: Error: boom
    at Object.<anonymous> (/Users/trentm/tm/node-cmdln/foo.js:15:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

@misterdjules Do you know if my suspicion is correct about node 0.12 no longer using `err.toString()` for `err.stack`?

**Comment by misterdjules** [comment]
@trentm Yes, it is correct if you don't define a `prepareStackTrace` method.

In this case, with v0.12.x, V8 [uses the `name` property to generate the content of the `stack` property](https://github.com/joyent/node/blob/v0.12/deps/v8/src/messages.js#L1247-L1260). With v0.10.x, [it calls `toString`](https://github.com/joyent/node/blob/v0.10/deps/v8/src/messages.js#L1056).

So one way to have a consistent behavior across node versions could be to define a `prepareStackTrace` method.

**Comment by trentm** [comment]
Julien also suggested a possible 'prepareStackTrace' to customize this: https://code.google.com/p/v8-wiki/wiki/JavaScriptStackTraceApi#Customizing_stack_traces

Perhaps could have that used in verror.js.

**Comment by trentm** [comment]
will be in 3.2.1
